# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-23 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignKeyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_int', models.IntegerField(auto_created=True, verbose_name=b'test')),
                ('t_char', models.CharField(blank=True, db_column=b'test_char', max_length=128, null=True, verbose_name=b'test char')),
            ],
            options={
                'verbose_name': 'A1',
                'verbose_name_plural': 'A1',
            },
        ),
        migrations.CreateModel(
            name='ManyToMany_rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ManyToManyAAndUniqueTogether',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_text', models.TextField(null=True, verbose_name=b'text')),
                ('t_bool', models.BooleanField(default=True, verbose_name=b'bool')),
                ('t_date', models.DateField(auto_now_add=True, verbose_name=b'date')),
                ('t_file', models.FileField(upload_to=b'', verbose_name=b'file')),
                ('t_url', models.URLField(verbose_name=b'url')),
                ('t_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManyToManyBAndOneToOneA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_side', models.ManyToManyField(through='inheritance.ManyToMany_rel', to='inheritance.ManyToManyAAndUniqueTogether')),
            ],
        ),
        migrations.CreateModel(
            name='OneToOneB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_side', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inheritance.ManyToManyBAndOneToOneA')),
            ],
        ),
        migrations.AddField(
            model_name='manytomanybandonetoonea',
            name='b_side',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inheritance.OneToOneB'),
        ),
        migrations.AddField(
            model_name='manytomanyaanduniquetogether',
            name='b_side',
            field=models.ManyToManyField(through='inheritance.ManyToMany_rel', to='inheritance.ManyToManyBAndOneToOneA'),
        ),
        migrations.AddField(
            model_name='manytomany_rel',
            name='a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inheritance.ManyToManyAAndUniqueTogether'),
        ),
        migrations.AddField(
            model_name='manytomany_rel',
            name='b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inheritance.ManyToManyBAndOneToOneA'),
        ),
        migrations.AddField(
            model_name='foreignkeymodel',
            name='t_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_a', to='inheritance.ManyToManyAAndUniqueTogether'),
        ),
        migrations.AlterUniqueTogether(
            name='manytomanyaanduniquetogether',
            unique_together=set([('t_file', 't_url')]),
        ),
    ]
